author: juuso@mail.com
description: Blog in Go

filesets:
    includes:
        - templates
        - public
        - README.md
        - LICENSE

settings:
        targetdir: ""
        build: |
            go(){ go "$@";} ; go install -v